/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(histogram_difference.h)                                    */
/* BINDTOOL_HEADER_FILE_HASH(173200425cca7bc42f21f40999fca864)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <openemissions/histogram_difference.h>
// pydoc.h is automatically generated in the build directory
#include <histogram_difference_pydoc.h>

template <typename freq_type>
void bind_histogram_difference_template(py::module& m, const char* classname)
{

    using histogram_difference    = gr::openemissions::histogram_difference<freq_type>;


    py::class_<histogram_difference, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<histogram_difference>>(m, classname)

        .def(py::init(&histogram_difference::make),
           py::arg("min"),
           py::arg("max"),
           py::arg("nbuckets") = 1024,
           D(histogram_difference,make)
        ) ;
}

void bind_histogram_difference(py::module& m)
{
    bind_histogram_difference_template<double>(m, "histogram_f64");
    bind_histogram_difference_template<float>(m, "histogram_f32");
    bind_histogram_difference_template<uint64_t>(m, "histogram_u64");
}
