/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pad_crop.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(20875316fce4c0f441fcdfd3a1a85a66)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <openemissions/pad_crop.h>
// pydoc.h is automatically generated in the build directory
#include <pad_crop_pydoc.h>

void bind_pad_crop(py::module& m)
{

    using pad_crop    = gr::openemissions::pad_crop;


    py::class_<pad_crop,
               gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pad_crop>>(m, "pad_crop")

        .def(py::init(&pad_crop::make),
           py::arg("itemsize"),
           py::arg("length"),
           py::arg("len_tag_key") = "packet_len",
           py::arg("pad") =  true,
           py::arg("crop") =  true,
           D(pad_crop,make)
        )
        



        ;




}








